apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: malware-aquarium
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM-SHA-1"]
    tls:
      enabled: false
  users:
    - name: graylog
      db: graylog
      passwordSecretRef:
        name: graylog-password
      roles:
        - name: dbOwner
          db: graylog
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: graylog-password
  namespace: mongodb
type: Opaque
stringData:
  password: graylog