apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mongodb-operator
  namespace: kube-system
spec:
  repo: https://mongodb.github.io/helm-charts
  chart: community-operator
  targetNamespace: mongodb
