apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    namespace: kube-system
    releaseName: cilium
    version: 1.12.0
    valuesInline:
      ipam:
        mode: kubernetes
      operator:
        replicas: 1
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
