apiVersion: batch/v1
kind: Job
metadata:
  name: deployer
  labels:
    app: deployer
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: vms/malware-network-host-local
    spec:
      dnsPolicy: None # ignore anything configured from the cluster
      dnsConfig:
        nameservers:
        - 10.244.0.254
        searches:
        - home.arpa
        options:
        - name: ndots
          value: "1"

      restartPolicy: Never
      containers:
        - name: deploy-malware
          image: docker.io/library/alpine
          command: ["/bin/sh", "-c"]
          envFrom:
            - configMapRef:
                name: deployer-config
                optional: false
            - secretRef:
                name: deployer-secret
                optional: false

          workingDir: /var/run/malware

          args:
          - |
            set -xe
            apk add --no-cache --quiet samba-client curl p7zip

            set +x
            curl -H "API-KEY: $MALWARE_BAZAR_API_KEY" -X POST --output mega.zip "$PAYLOAD_URL" -d "$QUERY_PARAMS"
            set -x

            mkdir payload
            cd payload

            7z x -p${MALWARE_ARCHIVE_PASSWORD} ../mega.zip

            PAYLOAD=$(ls | head -n 1)

            smbclient \
              --user $SMB_USERNAME \
              --password $SMB_PASSWORD \
              -c "cd $SMB_TARGET_DIR ; put $PAYLOAD" \
              $SMB_SHARE

          volumeMounts:
          - name: malware-volume
            mountPath: /var/run/malware

      volumes:
      - name: malware-volume
        emptyDir:
          # It's VERY important for this to be set to Memory. It will ensure
          # that the malware in this volume only exists in memory for the
          # lifetime of the pod.
          medium: Memory 
