apiVersion: batch/v1
kind: Job
metadata:
  name: deployer
  labels:
    app: deployer
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: vms/malware-network-host-local
    spec:
      dnsPolicy: None # ignore anything configured from the cluster
      dnsConfig:
        nameservers:
        - 10.244.0.254
        searches:
        - home.arpa
        options:
        - name: ndots
          value: "1"

      restartPolicy: Never

      containers:
        - name: deploy-malware
          image: docker.io/library/alpine
          command: ["/bin/sh", "-c"]

          env:
          - name: PAYLOAD_URL
            value: 'https://google.com'
          - name: SMB_USERNAME
            value: 'admin'
          - name: SMB_PASSWORD
            value: '123'
          - name: SMB_SHARE
            value: '\\10.244.0.105\C$'
          - name: SMB_TARGET_DIR
            value: 'Users\admin\Downloads\Recent'

          workingDir: /var/run/malware

          args:
          - |
            set -x
            apk add --no-cache --quiet samba-client

            wget $PAYLOAD_URL

            PAYLOAD=$(ls | head -n 1)

            smbclient \
              --user $SMB_USERNAME \
              --password $SMB_PASSWORD \
              -c "cd $SMB_TARGET_DIR ; put $PAYLOAD" \
              $SMB_SHARE

          volumeMounts:
          - name: malware-volume
            mountPath: /var/run/malware

          securityContext:
            capabilities:
              drop:
              - ALL
      
      volumes:
      - name: malware-volume
        emptyDir:
          # It's VERY important for this to be set to Memory. It will ensure
          # that the malware in this volume only exists in memory for the
          # lifetime of the pod.
          medium: Memory 
