apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deployer

resources:
- job.yaml

configMapGenerator:
  - name: deployer-config
    literals:
      - PAYLOAD_URL='https://mb-api.abuse.ch/api/v1/'
      - QUERY_PARAMS='query=get_file&sha256_hash=${MALWARE_BAZAR_SHA256_HASH}'
      - SMB_SHARE='\\${TARGET_MACHINE_ADDRESS}\C$'                              # should point to the machine targetted for malware deployment.
      - SMB_TARGET_DIR='Users\admin\Downloads\Recent'                           # the location where the malware is dropped. The watcher script executes files from this directory.

secretGenerator:
  - name: deployer-secret
    envs:
      # should contain the the variables contained in the given example file.
      #
      # MALWARE_BAZAR_API_KEY: the key providing access to the malware bazar api.
      # MALWARE_ARCHIVE_PASSWORD: the password used to encrypt the malware archive.
      # SMB_USERNAME: the SMB username for the target machine.
      # SMB_PASSWORD: the SMB password for the target machine.
      - deployer-secrets.env.example