apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: suricata
  name: suricata
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: suricata
  template:
    metadata:
      labels:
        app.kubernetes.io/name: suricata
    spec:
      containers:
        - name: suricata
          image: docker.io/jasonish/suricata:5.0
          command:
            - /usr/bin/suricata
          args:
          - -i
          - eth0
          - -v