apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: suricata
  name: suricata
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: suricata
  template:
    metadata:
      labels:
        app.kubernetes.io/name: suricata
        kubernetes.io/egress-bandwidth: "10M"
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { 
              "name": "suricata-malware-network",
              "namespace": "vms",
              "interface": "eth1"
            }
          ]
    spec:
      containers:
        - name: suricata
          image: docker.io/jasonish/suricata:5.0
          command:
            - /usr/bin/suricata
          args:
          - -i
          - eth0
          - -i
          - eth1
          - -v
          securityContext:
            privileged: true
            # capabilities:
              # drop:
              # - ALL
              # add:
              # - CAP_NET_ADMIN
          resources:
            requests:
              cpu: 4000m
              memory: 16Gi
            limits:
              cpu: 4000m
              memory: 16Gi
          volumeMounts:
          - name: suricata-config
            mountPath: /etc/suricata/suricata.yaml
            subPath: suricata.yaml
      volumes:
        - name: suricata-config
          configMap:
            name: suricata
