apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: falco
  namespace: kube-system
spec:
  repo: https://falcosecurity.github.io/charts
  chart: falco
  targetNamespace: falco
  valuesContent: |-
    ebpf:
      enabled: true

    falcosidekick:
      enabled: true
      webui:
        enabled: true