apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: grafana
  targetNamespace: grafana
  valuesContent: |-
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Admin
  
      auth:
        disable_login_form: true
  
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
  
      datasources:
        enabled: true
        defaultDatasourceEnabled: false
  
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          uid: loki-1
          orgId: 1
          url: http://loki.loki.svc.cluster.local:3100
          jsonData:
            maxLines: 5000
