apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  valuesContent: |-
    grafana:
      enabled: true
      serviceMonitor:
        enabled: true

      persistence:
        enabled: true

      grafana.ini:
        auth.anonymous:
          enabled: true
          org_role: Admin

        auth:
          disable_login_form: true

        # should be provisioned by the default kube dashboards
        dashboards:
          default_home_dashboard_path: /tmp/dashboards/k8s-resources-cluster.json

      additionalDataSources:
        - name: Loki
          type: loki
          uid: loki-1
          orgId: 1
          url: http://loki.loki.svc.cluster.local:3100
          jsonData:
            maxLines: 5000
            timeout: 600

    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
