apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: promtail
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: promtail
  targetNamespace: loki
    # version: 1.4.2
  valuesContent: |-
    extraPorts:
      syslog:
        name: tcp-syslog
        containerPort: 1514
        service:
          port: 80

    config:
      clients:
      - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

      snippets:
        extraScrapeConfigs: |
          # Add an additional scrape config for syslog
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
              labels:
                job: syslog
            relabel_configs:
              - source_labels:
                  - __syslog_message_hostname
                target_label: host
