apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tempo
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: tempo
  targetNamespace: loki
  valuesContent: |-
    persistence:
      enabled: true
    
    tempo:
      searchEnabled: true