apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- loki.namespace.yaml
- monitoring.namespace.yaml
- hubble-otelcollector.yaml

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    namespace: loki
    releaseName: loki
    valuesInline:
      config:
        server:
          # double the default message sizes. Seems we're logging big messages
          grpc_server_max_recv_msg_size: 150000000
          grpc_server_max_send_msg_size: 150000000
        limits_config:
          max_entries_limit_per_query: 5000
      persistence:
        enabled: true


  - name: promtail
    repo: https://grafana.github.io/helm-charts
    namespace: loki
    releaseName: promtail
    valuesInline:
      config:
        clients:
        - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
      
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    namespace: loki
    releaseName: tempo
    valuesInline:
      persistence:
        enabled: true
      tempo:
        searchEnabled: true
      
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    releaseName: monitoring
    includeCRDs: true
    valuesInline:
      grafana:
        enabled: true

        testFramework:
          enabled: false

        serviceMonitor:
          enabled: true

        persistence:
          enabled: true

        grafana.ini:
          auth.anonymous:
            enabled: true
            org_role: Admin

          auth:
            disable_login_form: true

          # should be provisioned by the default kube dashboards
          dashboards:
            default_home_dashboard_path: /tmp/dashboards/k8s-resources-cluster.json

        additionalDataSources:
          - name: Loki
            type: loki
            uid: loki-1
            orgId: 1
            url: http://loki.loki.svc.cluster.local:3100
            jsonData:
              maxLines: 5000
              timeout: 600
          - name: Tempo
            type: tempo
            uid: tempo-1
            url: http://tempo.loki.svc.cluster.local:4317
            jsonData:
              lokiSearch:
                datasourceUid: loki-1
              tracesToLogs:
                datasourceUid: loki-1

      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 50Gi