apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: suricata-egress
  namespace: suricata
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    # - toServices:
    #     - k8sServiceSelector:
    #         selector:
    #           matchLabels:
    #             app: graylog
    #         namespace: graylog
    #   toPorts:
    #     - ports:
    #         - port: "12201"
    #           protocol: TCP

    - toPorts:
      - ports:
        - port: ANY
        rules:
            http:
              - method: "GET"
    - toPorts:
      - ports:
          - port: "53"
            protocol: ANY
    #     rules:
    #       dns:
    #         - matchPattern: "*"
      # toCIDR:
      #   - 8.8.8.8/32
      #   - 10.43.0.10/16