apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: suricata-egress
  namespace: suricata
spec:
  endpointSelector: {}
  # ingress blocked
  ingress:
    - {}
  egress:
    # allow L3/L4 to the world
    - toEntities:
      - world
      toPorts:
      - ports:
        - port: "53"
          protocol: ANY
        rules:
          dns:
            - matchPattern: "*"

      - ports:
        - port: "443"
          protocol: ANY

      - ports:
        - port: "80"
          protocol: ANY
        rules:
          http:
            - method: ".*"

    # allow L3/L4 to the cluster DNS for monitoring domains
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s:k8s-app: kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: ANY
        rules:
          dns:
            - matchPattern: "*.loki.svc.cluster.local"
            - matchPattern: "*.grr.svc.cluster.local"

    # allow sending logs to loki
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: loki
          k8s:app: loki
      toPorts:
      - ports:
        - port: "3100"
          protocol: TCP
        rules:
          http:
            - method: "POST"
              path: "/loki/api/v1/push"

    # allow grr connectivity
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: grr
          k8s:app: grr
      toPorts:
      - ports:
        - port: "8080"
          protocol: TCP
