apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    namespace: tempo
    releaseName: tempo
    valuesInline:
      persistence:
        enabled: true
      tempo:
        searchEnabled: true
      