apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
- namespace.yaml

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    namespace: loki
    releaseName: loki
    version: 3.2.1
    valuesInline:
      loki:
        auth_enabled: false
        server:
          # double the default message sizes. Seems we're logging big messages
          grpc_server_max_recv_msg_size: 150000000
          grpc_server_max_send_msg_size: 150000000
        limits_config:
          max_entries_limit_per_query: 5000
        commonConfig:
          replication_factor: 1
      read:
        replicas: 1
      write:
        replicas: 1
      monitoring:
        selfMonitoring:
          enabled: false
          grafanaAgent:
            installOperator: false
