apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    namespace: loki
    releaseName: promtail
    valuesInline:
      config:
        clients:
        - url: http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push
