apiVersion: v1
kind: Service
metadata:
  name: big-red-button
  labels:
    app: big-red-button
spec:
  type: ClusterIP
  selector:
    app: big-red-button
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
