apiVersion: v1
kind: Pod
metadata:
  name: malware-deployer
  labels:
    app: malware-deployer
  annotations:
    v1.multus-cni.io/default-network: vms/bridged-malware-network-with-firewall-and-dhcp
    # k8s.v1.cni.cncf.io/networks: |
    #   [
    #     {
    #       "name": "bridged-malware-network-with-firewall",
    #       "namespace": "vms",
    #       "ips": [
    #         "10.244.0.2/24"
    #       ],
    #       "default": true,
    #       "routes": [
    #         { "dst": "0.0.0.0/0", "gw": "10.244.0.254" }
    #       ]
    #     }
    #   ]
spec:
  containers:
  - image: alpine
    name: malware-deployer
    args:
    - sleep
    - infinity
  dnsPolicy: None # ignore the cluster default
  dnsConfig:
    nameservers:
    - 10.244.0.254