apiVersion: v1
kind: Namespace
metadata:
  name: rng

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
  labels:
    app: rng
  namespace: rng
spec:
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - image: docker.io/library/bash
        name: rng
        args:
        - "-c"
        - |
          while true; do
            echo "timestamp=$(date -Iseconds --utc) random=$(($RANDOM % 10))"
            sleep 1
          done