# allows access to the generated config as a normal user
write-kubeconfig-mode: "0644"

# pod and service IPv4 ranges used within the cluster
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"

# do not install the default flannel backend. We will deploy cilium separately
flannel-backend: "none"

# required to avoid conflicts with ciliums enforcement of NetworkPolicies.
disable-network-policy: true

# These services are not required.
disable:
- traefik
- servicelb