apiVersion: k3d.io/v1alpha4
kind: Simple

image: docker.io/rancher/k3s:v1.24.4-k3s1

kubeAPI:
  host: "localhost" # important for the `server` setting in the kubeconfig
  hostPort: "6443"

volumes:
  - volume: var-lib-rancher-k3s-agent-containerd-server-0:/var/lib/rancher/k3s/agent/containerd
    nodeFilters:
      - server:0

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer