apiVersion: v1
kind: Service
metadata:
  labels:
    app: ntopng
  name: ntopng
spec:
  clusterIP: None
  selector:
    app: ntopng
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000