apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- hubble-otelcollector.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    releaseName: monitoring
    includeCRDs: true
    valuesInline:
      grafana:
        enabled: true

        testFramework:
          enabled: false

        serviceMonitor:
          enabled: true

        persistence:
          enabled: true

        grafana.ini:
          auth.anonymous:
            enabled: true
            org_role: Admin

          auth:
            disable_login_form: true

          # should be provisioned by the default kube dashboards
          dashboards:
            default_home_dashboard_path: /tmp/dashboards/k8s-resources-cluster.json

        additionalDataSources:
          - name: Loki
            type: loki
            uid: loki-1
            orgId: 1
            url: http://loki-read.loki.svc.cluster.local:3100
            jsonData:
              maxLines: 5000
              timeout: 600
          - name: Tempo
            type: tempo
            uid: tempo-1
            url: http://tempo.tempo.svc.cluster.local:4317
            jsonData:
              lokiSearch:
                datasourceUid: loki-1
              tracesToLogs:
                datasourceUid: loki-1

      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 50Gi
