apiVersion: v1
kind: Service
metadata:
  labels:
    app: grr
  name: grr-headless
spec:
  clusterIP: None
  selector:
    app: grr
  ports:
  - name: http-admin
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http-client
    port: 8080
    protocol: TCP
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grr
  name: grr
spec:
  selector:
    app: grr
  ports:
  - name: http-admin
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http-client
    port: 8080
    protocol: TCP
    targetPort: 8080