apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grr
  labels:
    app: grr

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grr
  serviceName: grr
  updateStrategy:
    type: OnDelete

  volumeClaimTemplates:
  - metadata:
      name: var-lib-mysql
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: grr-client-installers
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: grr-etc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  template:
    metadata:
      labels:
        app: grr
    spec:
      initContainers:
      - image: docker.io/grrdocker/grr:v3.4.6.0
        name: prep-etc
        args:
        - bash
        - -c
        - |
          set -x
          if [[ ! -e "/grr-etc/grr-server.yaml" ]]; then
            cp -v /usr/share/grr-server/install_data/etc/* /grr-etc/
          fi
        volumeMounts:
        - name: grr-etc
          mountPath: /grr-etc
      containers:
      - image: docker.io/grrdocker/grr:v3.4.6.0
        name: grr-server
        envFrom:
        - configMapRef:
            name: grr
        - secretRef:
            name: grr
        ports:
        - name: http-admin
          containerPort: 8000
          protocol: TCP
        - name: http-clients
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: var-lib-mysql
          mountPath: /var/lib/mysql
        - name: grr-client-installers
          mountPath: /usr/share/grr-server/executables/installers
        - name: grr-etc
          mountPath: /usr/share/grr-server/install_data/etc/