apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v0.53.1/kubevirt-cr.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.50.0/cdi-cr.yaml
  - clone-rbac.yaml
  - vm-images.namespace.yaml
  - vms.namespace.yaml