apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridged-malware-network-with-firewall
  namespace: vms
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "bridged-malware-network-with-firewall",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "mal0",
          "vlan": 1,
          "ipam": {
            "type": "static",
            "capabilities": {
              "ips": true
            }
          }
        },
        {
          "type": "firewall",
          "backend": "iptables",
          "ingressPolicy": "same-bridge"
        }
      ]
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridged-malware-network-with-firewall-and-dhcp
  namespace: vms
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "bridged-malware-network-with-firewall-and-dhcp",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "mal0",
          "vlan": 1,
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "10.244.0.0/24",
                  "rangeStart": "10.244.0.2",
                  "rangeEnd": "10.244.0.200",
                  "gateway": "10.244.0.254"
                }
              ]
            ],
            "routes": [
              { "dst": "0.0.0.0/0" }
            ]
          }
        },
        {
          "type": "firewall",
          "backend": "iptables",
          "ingressPolicy": "same-bridge"
        }
      ]
    }