apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: malware-network
  namespace: vms
spec: 
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "malware-network",
      "type": "bridge",
      "bridge": "mal0",
      "macspoofchk": true,
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.244.0.254/32"
            },
            {
              "subnet": "10.244.0.0/24",
              "rangeStart": "10.244.0.2",
              "rangeEnd": "10.244.0.200",
              "gateway": "10.244.0.254"
            }
          ]
        ]
      }
    }