apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: malware-network-static
  namespace: vms
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "malware-network-static",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "mal0",
          "ipam": {
            "type": "static",
            "capabilities": {
              "ips": true
            }
          }
        }
      ]
    }

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: malware-network-host-local
  namespace: vms
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "malware-network-host-local",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "mal0",
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "10.244.0.0/24",
                  "rangeStart": "10.244.0.2",
                  "rangeEnd": "10.244.0.200",
                  "gateway": "10.244.0.254"
                }
              ]
            ],
            "routes": [
              { "dst": "0.0.0.0/0" }
            ]
          }
        }
      ]
    }
