apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: malware-network
spec: 
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "malware-network",
      "type": "bridge",
      "bridge": "mal0",
      "isDefaultGateway": true,
      "ipam": {
        "type": "host-local",
        "subnet": "10.234.0.0/16"
      }
    }