apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: windows-10-test-vm-1
  name: windows-10-test-vm-1
  namespace: vms
spec:
  running: true
  template:
      metadata:
        labels:
          kubevirt.io/vm: windows-10-test-vm-1
      spec:
        dnsPolicy: None # ignore anything configured from the cluster
        dnsConfig:
          nameservers:
          - 10.244.0.254
          searches:
          - home.arpa
          options:
          - name: ndots
            value: "1"
        domain:
          clock:
            timer:
              hpet:
                present: false
              hyperv: {}
              pit:
                tickPolicy: delay
              rtc:
                tickPolicy: catchup
            utc: {}
          cpu:
            cores: 2
          devices:
            autoattachPodInterface: false
            disks:
              - disk:
                  bus: virtio
                name: pvcdisk
            interfaces:
            - model: e1000
              name: malware-network
              bridge: {}
            tpm: {}
          features:
            acpi: {}
            apic: {}
            hyperv:
              relaxed: {}
              spinlocks:
                spinlocks: 8191
              vapic: {}
            smm: {}
          firmware:
            uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
          resources:
            requests:
              memory: 4Gi
        networks:
        - name: malware-network
          multus:
            default: true
            networkName: vms/malware-network-host-local
        terminationGracePeriodSeconds: 0
        volumes:
        - name: pvcdisk
          ephemeral:
            persistentVolumeClaim:
              claimName: windows-10.2022-07-03.10-50-23