apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: windows-server-2019
  name: windows-server-2019
  namespace: vms
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: disk-windows
    spec:
      source:
        pvc:
          namespace: vm-images
          name: windows-2019
      pvc:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 70Gi
  template:
    metadata:
      labels:
        kubevirt.io/vm: windows-server-2019
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: pvcdisk
          interfaces:
          - model: e1000
            name: malware-network
            bridge: {}
          tpm: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              secureBoot: true
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: malware-network
        multus:
          networkName: malware-network
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pvcdisk
        dataVolume:
          name: disk-windows
  