apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: windows-10
  name: windows-10
  namespace: vms
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: windows-10
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 4
        devices:
          autoattachPodInterface: false
          disks:
            - disk:
                bus: virtio
              name: pvcdisk
          interfaces:
          - model: e1000
            name: default
            bridge: {}
          tpm: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        resources:
          requests:
            memory: 8Gi
      networks:
      - name: default
        multus:
          default: true
          networkName: vms/malware-network-host-local
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pvcdisk
        ephemeral:
          persistentVolumeClaim:
            claimName: windows-10.2022-06-22.14-06-46
