apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: graylog
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - image: docker.io/graylog/graylog:4.3
        name: graylog
        envFrom:
        - configMapRef:
            name: graylog
        - secretRef:
            name: graylog
        ports:
        - containerPort: 9000
          name: http
          protocol: "TCP"
        - containerPort: 8514
          name: syslog-tcp
          protocol: "TCP"
        - containerPort: 8514
          name: syslog-udp
          protocol: "UDP"
        - containerPort: 12201
          name: gelf-tcp
          protocol: "TCP"
        - containerPort: 12201
          name: gelf-udp
          protocol: "UDP"