apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
  name: graylog
  namespace: graylog
spec:
  selector:
    app: graylog
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: syslog-tcp
    port: 8514
    protocol: TCP
    targetPort: 8514
  - name: syslog-udp
    port: 8514
    protocol: UDP
    targetPort: 8514
  - name: gelf-tcp
    port: 12201
    protocol: TCP
    targetPort: 12201
  - name: gelf-udp
    port: 12201
    protocol: UDP
    targetPort: 12201

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
  name: graylog-headless
  namespace: graylog
spec:
  clusterIP: None
  selector:
    app: graylog
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: syslog-tcp
    port: 8514
    protocol: TCP
    targetPort: 8514
  - name: syslog-udp
    port: 8514
    protocol: UDP
    targetPort: 8514
  - name: gelf-tcp
    port: 12201
    protocol: TCP
    targetPort: 12201
  - name: gelf-udp
    port: 12201
    protocol: UDP
    targetPort: 12201