apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: graylog

resources:
- graylog.namespace.yaml
- graylog.deployment.yaml
- graylog.service.yaml

configMapGenerator:
- name: graylog
  literals:
  - GRAYLOG_MONGODB_URI=mongodb+srv://graylog:graylog@malware-aquarium-svc.mongodb.svc.cluster.local/graylog?ssl=false

secretGenerator:
- name: graylog
  literals:
  - GRAYLOG_PASSWORD_SECRET=sargantpepperwelcomesyou
  - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  - GRAYLOG_ELASTICSEARCH_HOSTS=http://elastic:admin@malware-aquarium-es-http.elastic.svc.cluster.local:9200